/*
 * kamitext C ABI.
 *
 * Check kami_abi_version() before use. All query results point into
 * engine-owned arenas and are invalidated by ANY subsequent call on the same
 * engine — copy out what you need before calling again or yielding control.
 * Strings are (ptr, len) UTF-8, never NUL-terminated.
 */

#ifndef KAMI_CORE_H
#define KAMI_CORE_H

/* Generated by cbindgen from kamitext; do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// ABI version. Bumped on any breaking layout or semantic change.
#define KAMI_ABI_VERSION 2

#define KAMI_OK 0

// Out-of-bounds, reversed or scalar-splitting range on a mutating call.
#define KAMI_ERR_INVALID_RANGE -1

// Input bytes are not valid UTF-8.
#define KAMI_ERR_INVALID_UTF8 -2

// A required pointer argument was NULL.
#define KAMI_ERR_NULL -3

// The engine was poisoned by an earlier panic; re-create it.
#define KAMI_ERR_POISONED -4

// An internal panic was caught; the engine is now poisoned.
#define KAMI_ERR_INTERNAL -5

#define KAMI_ELEMENT_TASK 0

#define KAMI_ELEMENT_LINK 1

#define KAMI_ELEMENT_IMAGE 2

#define KAMI_ELEMENT_FENCE 3

#define KAMI_ELEMENT_WIKILINK 4

// Opaque engine handle (Rustonomicon opaque-struct pattern). Only ever used
// behind a pointer; cbindgen emits a bare forward declaration.
typedef struct KamiEngine KamiEngine;

typedef struct KamiOptions {
  // Bitflags: 1 = tables, 2 = task lists, 4 = strikethrough, 8 = wikilinks.
  uint32_t extensions;
  // 0 = none (reader), 1 = line (default), 2 = block, 3 = element.
  uint32_t reveal;
} KamiOptions;

typedef struct KamiByteRange {
  uint32_t start;
  uint32_t end;
} KamiByteRange;

typedef struct KamiPatch {
  const struct KamiByteRange *ranges;
  size_t len;
  uint64_t generation;
} KamiPatch;

typedef struct KamiSegment {
  uint32_t start;
  uint32_t end;
  uint32_t utf16_start;
  uint32_t utf16_end;
  // Kind bit set (stable ids).
  uint64_t kinds;
  // 1 = concealed under the current reveal state.
  uint8_t concealed;
  uint8_t _pad[7];
} KamiSegment;

typedef struct KamiSegments {
  const struct KamiSegment *ptr;
  size_t len;
  uint64_t generation;
} KamiSegments;

typedef struct KamiElement {
  uint32_t id;
  uint32_t start;
  uint32_t end;
  // KAMI_ELEMENT_* tag. Unknown tags must be ignored.
  uint32_t kind;
  // Task: 1 = checked. Other kinds: 0.
  uint8_t checked;
  uint8_t _pad[3];
  // Link dest / image src / fence info byte range; 0-width when absent.
  uint32_t aux_start;
  uint32_t aux_end;
} KamiElement;

typedef struct KamiElements {
  const struct KamiElement *ptr;
  size_t len;
  uint64_t generation;
} KamiElements;

// Borrowed UTF-8 view into engine memory. NOT NUL-terminated.
typedef struct KamiStr {
  const uint8_t *ptr;
  size_t len;
} KamiStr;

typedef struct KamiEditOp {
  uint32_t start;
  uint32_t end;
  // Replacement text, engine-owned, NOT NUL-terminated.
  struct KamiStr text;
} KamiEditOp;

typedef struct KamiEditPlan {
  // 1 when a plan exists; 0 = no plan (not an error).
  uint8_t has_plan;
  uint8_t _pad[3];
  // Caret byte offset after applying the edits back-to-front.
  uint32_t caret;
  const struct KamiEditOp *edits;
  size_t edits_len;
  uint64_t generation;
} KamiEditPlan;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Adapters must check this before use.
uint32_t kami_abi_version(void);

// Creates an engine from UTF-8 text. Returns NULL on invalid UTF-8, invalid
// options, or internal panic.
struct KamiEngine *kami_engine_new(const uint8_t *text,
                                   size_t text_len,
                                   struct KamiOptions options);

// Frees the engine. NULL is a no-op. All outstanding views die with it.
void kami_engine_free(struct KamiEngine *engine);

// Current view-invalidation counter. Every `with_cell` entry point (all
// mutating and query calls) bumps it; the read-only observers
// (`kami_generation`, `kami_len_bytes`, `kami_len_utf16`,
// `kami_last_error_message`, `kami_abi_version`) do NOT bump it and do not
// invalidate outstanding views — deliberately, so this counter can validate
// a held view, and as a documented leniency over the strict
// any-call-invalidates rule (conformant adapters are unaffected).
uint64_t kami_generation(const struct KamiEngine *engine);

int32_t kami_apply_edit(struct KamiEngine *engine,
                        uint32_t start,
                        uint32_t end,
                        const uint8_t *replacement,
                        size_t replacement_len,
                        struct KamiPatch *out_patch);

int32_t kami_set_selection(struct KamiEngine *engine,
                           uint32_t start,
                           uint32_t end,
                           struct KamiPatch *out_patch);

int32_t kami_segments_in(struct KamiEngine *engine,
                         uint32_t start,
                         uint32_t end,
                         struct KamiSegments *out);

int32_t kami_elements_in(struct KamiEngine *engine,
                         uint32_t start,
                         uint32_t end,
                         struct KamiElements *out);

// Borrowed view of the whole document text (UTF-8, engine-owned).
int32_t kami_text(struct KamiEngine *engine, struct KamiStr *out);

// Read-only observer (see `kami_generation`): no generation bump, no view
// invalidation. Returns 0 for a NULL or poisoned engine.
uint32_t kami_len_bytes(const struct KamiEngine *engine);

// Read-only observer (see `kami_generation`): no generation bump, no view
// invalidation. Returns 0 for a NULL or poisoned engine.
uint32_t kami_len_utf16(const struct KamiEngine *engine);

int32_t kami_byte_to_utf16(struct KamiEngine *engine, uint32_t offset, uint32_t *out);

// Rounds down to a scalar start — a query, never an error.
int32_t kami_utf16_to_byte(struct KamiEngine *engine, uint32_t offset, uint32_t *out);

// List/task/quote continuation for Enter at `at`. `has_plan == 0`
// with KAMI_OK means "insert a plain newline yourself".
int32_t kami_newline_plan(struct KamiEngine *engine, uint32_t at, struct KamiEditPlan *out);

// Flips the task checkbox whose item contains `at`.
int32_t kami_toggle_task_plan(struct KamiEngine *engine, uint32_t at, struct KamiEditPlan *out);

// Diagnostic message for the last error on this engine. Empty when the last
// call succeeded. The view is engine-owned and dies at the next `with_cell`
// call; it carries no generation token (same lifetime rule applies —
// read-only observer, see `kami_generation`).
struct KamiStr kami_last_error_message(const struct KamiEngine *engine);

// Test hook: forces an internal panic so adapters can exercise poisoning.
// Hidden from normal use; kept in release builds for adapter conformance
// suites.
int32_t kami_debug_force_panic(struct KamiEngine *engine);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KAMI_CORE_H */
